/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "guxottbhtkdnsstkexgm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1eG90dGJodGtkbnNzdGtleGdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1NDI3MTEsImV4cCI6MjA4ODExODcxMX0.zD3PITeuVN2ifsBlaPIs5HEPU34DV0oBjY0K--iUEQ8"